name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build a debian
      run: sbt debian:packageBin
    - name: Build unversal packages (zip | tar.gz | tar.gz)
      run: |
        sbt universal:packageBin
        sbt universal:packageZipTarball
        sbt universal:packageXzTarball
        mv target/universal/traffic-lights-service-*.zip target/
        mv target/universal/traffic-lights-service-*.tgz target/
        mv target/universal/traffic-lights-service-*.txz target/
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: |
          target/traffic-lights-service-*.deb
          target/traffic-lights-service-*.zip
          target/traffic-lights-service-*.tgz
          target/traffic-lights-service-*.txz